### ISSUE TITLE
[minor] Wording suggestions for confirmation boxes

### ISSUE THREAD

**Issue by dan1982code** [nvdaes/clipContentsDesigner#6]
Hi,

I have suggestions for the confirmation box that shows up when copying with the "Confirm to emulate copy" checkbox is checked.

The current window is

---
Please, confirm if you want to copy to the clipboard

OK Cancel
---

My suggestion is

---
Copy to clipboard?

Yes No
---

Getting the 'please,' out of there saves some reading time, and yes/no would be more clear than OK/cancel.

Similar suggestions for the other three confirm boxes (cut, add, clear).

Thank you!

**Comment by nvdaes** [comment]
I will delete the please, but I prefer to use a question which can be answered with OK/cancel, so that Escape key can be pressed, not just tab, for usability and flexibility using the keyboard.

**Comment by dan1982code** [comment]
Good one, thanks! I hadn't considered the escape key -- sorry.

**Comment by nvdaes** [comment]
Hi, I'm thinking we can let please without deleting. The reason is that this would require new translations and for now the deletion could produce inconsistencies between language. This is just a word. Anyway, if you still think it should be removed, I will do it. I'm not an English speaker and I'm not sure about the effects. Waiting for your useful comments. Thanks.

**Comment by nvdaes** [comment]
I'll close this now. If you have other important comments, please reopen it. Thanks.
